name: Build static ffmpeg

on:
  push:
  pull_request:

jobs:
  package-alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker run -v $GITHUB_WORKSPACE:/project -w /project -e ARCH=$ARCH alpine:latest /bin/sh ./build-alpine.sh
          mkdir artifacts
          mv ffmpeg-*-audio-alpine-* artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ffmpeg-alpine-${{ env.ARCH }}
          path: artifacts/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - package-alpine
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: ffmpeg-alpine-x86_64
          path: artifacts/

      - name: Make tarballs
        run: |
          mkdir artifacts/release/
          cd artifacts/
          dirs=$(find . -name 'ffmpeg-*' -type d)
          for dir in $dirs
          do
            name=$(basename $dir)
            tar cvzf release/$name.tar.gz $dir
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
